CREATE TABLE `process_order_operation_data`
(
    `ProcessOrder`                       varchar(20) NOT NULL,
    `SpaceMasterRecipeGroup`             varchar(10) NOT NULL,
    `SpaceMasterRecipe`                  varchar(20) NOT NULL,
    `SpaceMasterRecipeInternalVersion`   varchar(8) NOT NULL,
    `SpaceMasterRecipeSequence`          varchar(6) NOT NULL,
    `MstrRcpOperationIntVersion`         varchar(8) NOT NULL,
    `SpaceMasterRecipeOperationIntID`    varchar(8) NOT NULL,
    `OperationText`                      varchar(40) DEFAULT NULL,
    `PlainLongText`                      varchar(255) DEFAULT NULL,
    `WorkCenterTypeCode`                 varchar(6) DEFAULT NULL,
    `WorkCenter`                         varchar(20) DEFAULT NULL,
    `WorkCenterBaseCamp`                 varchar(20) DEFAULT NULL,
    `StandardInputQuantity`              varchar(20) DEFAULT NULL,
    `StandardInputQuantityUnit`          varchar(5) DEFAULT NULL,
    `StandardOutputQuantity`             varchar(20) DEFAULT NULL,
    `StandardOutputQuantityUnit`         varchar(5) DEFAULT NULL,
    `StandardOperatingTime`              varchar(20) DEFAULT NULL,
    `StandardOperatingTimeUnit`          varchar(5) DEFAULT NULL,
    `PlannedStartDate`                   varchar(20) DEFAULT NULL,
    `PlannedStartTime`                   varchar(20) DEFAULT NULL,
    `PlanndEndDate`                      varchar(20) DEFAULT NULL,
    `PlanndEndTime`                      varchar(20) DEFAULT NULL,
    `ActualInputQuantity`                varchar(20) DEFAULT NULL,
    `ActualInputQuantityUnit`            varchar(5) DEFAULT NULL,
    `ActualOutputQuantity`               varchar(20) DEFAULT NULL,
    `ActualOutputQuantityUnit`           varchar(5) DEFAULT NULL,
    `ActualOperatingTime`                varchar(20) DEFAULT NULL,
    `ActualOperatingTimeUnit`            varchar(5) DEFAULT NULL,
    `ActualStartDate`                    varchar(20) DEFAULT NULL,
    `ActualStartTime`                    varchar(20) DEFAULT NULL,
    `ActualEndDate`                      varchar(20) DEFAULT NULL,
    `ActualEndTime`                      varchar(20) DEFAULT NULL,
    `CreatedDateTime`                    varchar(20) DEFAULT NULL,
    `LastModifiedDateTime`               varchar(20) DEFAULT NULL, 
    PRIMARY KEY (`ProcessOrder`, `SpaceMasterRecipeGroup`, `SpaceMasterRecipe`, `SpaceMasterRecipeInternalVersion`, `SpaceMasterRecipeSequence`, `MstrRcpOperationIntVersion`, `SpaceMasterRecipeOperationIntID`),
    CONSTRAINT `ProcessOrderOperationData_fk` FOREIGN KEY (`SpaceMasterRecipeGroup`, `SpaceMasterRecipe`, `SpaceMasterRecipeInternalVersion`) REFERENCES `master_recipe_for_space_products_header_data` (`SpaceMasterRecipeGroup`, `SpaceMasterRecipe`, `SpaceMasterRecipeInternalVersion`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
